[package]
name = "trackground"
version = "0.1.0"
edition = "2021"

[dependencies]
mpris = "2.0.1"
magick_rust = "1.0.0"
reqwest = { version = "0.12.5", features = ["blocking"] }
image = "0.25.2"
wallpaper = "3.2.0"
